services:
  web:
    image: poljpocket/wordpress:php7.4
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - database
    environment:
      WEB_USER_ID: 1000
      WEB_GROUP_ID: 1000
    volumes:
      - files:/var/www/html:rw
      - ./backup:/backup:rw
      - ./themes:/var/www/html/wp-content/themes:rw
      - ./plugins:/var/www/html/wp-content/plugins:rw
  database:
    image: mariadb:10.6
    volumes:
      - database:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - "127.0.0.1:8081:80"
    environment:
      PMA_USER: docker
      PMA_PASSWORD: docker
      PMA_PORT: 3306
      PMA_HOST: database
volumes:
  database:
  files:
